# Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lode_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# Estratégia de criação das tabelas automáticas (Code-First)
spring.jpa.hibernate.ddl-auto=update

# Mostrar os comandos SQL no terminal para ajudar a debugar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do CORS (Altere aqui se o seu Frontend rodar em outra porta)
cors.allowed-origins=http://localhost:5173